spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    # url: jdbc:postgresql://localhost:5432/workmanager
    url: ${DB_CONNECTION_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    driver-class-name: org.postgresql.Driver
    url: ${DB_CONNECTION_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "*"

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin
