spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://workmanagerpostgres:5432/workmanagerpostgres?stringtype=unspecified
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://workmanagerpostgres:5432/workmanagerpostgres?stringtype=unspecified
    user: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin